# Generated by Django 2.2.3 on 2019-08-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='signature',
            new_name='user',
        ),
    ]
