# Generated by Django 2.2.3 on 2019-10-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='signature',
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_calendar.Calendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
