# Generated by Django 2.2.3 on 2019-10-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calendar', '0002_auto_20191008_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auth_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
