# Generated by Django 2.2.3 on 2019-09-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calendar', '0002_auto_20190806_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
