# Generated by Django 2.2.3 on 2019-10-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calendar', '0003_event_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='auth_code',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
