# Generated by Django 2.2.3 on 2019-11-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calendar', '0004_auto_20191028_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(max_length=15),
        ),
    ]
